# intfmt.R --------------------------------------------------------------------------------------------------------
# 2023-01-15T18:46Z-5
# Por Fabrício Kury
# fab em kury.dev

#' @export
usn <- function(n, decimals = 0) {
  sapply(n, function(e) {
    if(is.na(e))
      return(e)
    # usn()'s decimals behave like round()'s digits, but comma()'s precision is different.
    scales::comma(e, 10^(-decimals))
  })
}

#' @export
intn <- function(n, decimals = 0) {
  sapply(n, function(e) {
    if(is.na(e))
      return(e)
    # intn()'s decimals behave like round()'s digits, but comma()'s precision is different.
    scales::comma(e, 10^(-decimals), decimal.mark = ',', big.mark = '.')
  })
}

#' @export
plural <- function(n) {
  ifelse(n == 1, '', 's')
}

# TODO: Mover a função abaixo para outra biblioteca.
#' @export
joincmp <- function(a, b, a_name = 'A', b_name = 'B', skip_a = FALSE, skip_b = FALSE, verbose = TRUE) {
  # Computes the overlap between two vectors. The name comes from "join comparison," from this function's original
  # intended purpose of predicting duplicates generated by SQL joins.
  # TODO: Handle the case when a or b have duplicates. Report the fact and deduplicate before computing the overlaps.
  a_varname <- deparse(substitute(a))
  b_varname <- deparse(substitute(b))
  if(!skip_a)
    a <- unique(a)
  if(!skip_b)
    b <- unique(b)
  intersection_len <- length(intersect(a, b))
  union_len <- length(union(a, b))

  if(verbose) {
    a_pl <- ifelse(length(a)==1, '', 's')
    b_pl <- ifelse(length(b)==1, '', 's')
    console('\n',
      a_name, ' = ', a_varname, '\n', b_name, ' = ', b_varname, '\n',
      a_name, ' and ', b_name, ' share ', usn(intersection_len), ' item', ifelse(intersection_len==1, '', 's'), ', ',
      'which are ', round(100*intersection_len/union_len), '% of the ', usn(union_len), ' item',
      ifelse(union_len==1, '', 's'), ' in the union.',
      ifelse(union_len-intersection_len>0,
        paste0(' ', usn(union_len-intersection_len), ' ',
          ifelse(union_len-intersection_len==1, 'is', 'are'),
          ' not shared.'),
        ''),
      '\n',
      a_name, ' has ', usn(length(a)), ' item', a_pl, ', ', round(100*intersection_len/length(a), 2),
      '% of which ', ifelse(round(100*intersection_len/length(a), 0)==1, 'is', 'are'), ' shared.',
      ifelse(length(a)-intersection_len>0, paste0(' (', usn(length(a)-intersection_len), ' not shared)'), ''),
      '\n',
      b_name, ' has ', usn(length(b)), ' item', b_pl, ', ', round(100*intersection_len/length(b), 2),
      '% of which ', ifelse(round(100*intersection_len/length(b), 0)==1, 'is', 'are'), ' shared.',
      ifelse(length(b)-intersection_len>0, paste0(' (', usn(length(b)-intersection_len), ' not shared)'), ''))
  }

  return(list(
    i_len = intersection_len,
    u_len = union_len))
}

#' @export
filter_out <- function(df, ...) {
  expr <- rlang::enquos(...)
  dplyr::filter(df, !(!!expr[[1]]))
}
